=== janhybs/ci-hpc/src/cihpc/common/utils/git/webhooks/push_hook/push_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/PushWebhook",
    "definitions": {
        "PushWebhook": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "ref": {
                    "type": "string"
                },
                "before": {
                    "type": "string"
                },
                "after": {
                    "type": "string"
                },
                "created": {
                    "type": "boolean"
                },
                "deleted": {
                    "type": "boolean"
                },
                "forced": {
                    "type": "boolean"
                },
                "base_ref": {
                    "type": "null"
                },
                "compare": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ],
                    "qt-uri-extensions": [
                        ".e87eead22e74"
                    ]
                },
                "commits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Commit"
                    }
                },
                "head_commit": {
                    "$ref": "#/definitions/Commit"
                },
                "repository": {
                    "$ref": "#/definitions/Repository"
                },
                "pusher": {
                    "$ref": "#/definitions/Pusher"
                },
                "sender": {
                    "$ref": "#/definitions/Sender"
                }
            },
            "required": [],
            "title": "PushWebhook"
        },
        "Commit": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "tree_id": {
                    "type": "string"
                },
                "distinct": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string",
                    "format": "date-time"
                },
                "url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "author": {
                    "$ref": "#/definitions/Author"
                },
                "committer": {
                    "$ref": "#/definitions/Author"
                },
                "added": {
                    "type": "array",
                    "items": {}
                },
                "removed": {
                    "type": "array",
                    "items": {}
                },
                "modified": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [],
            "title": "Commit"
        },
        "Author": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            },
            "required": [],
            "title": "Author"
        },
        "Pusher": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            },
            "required": [],
            "title": "Pusher"
        },
        "Repository": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "node_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "private": {
                    "type": "boolean"
                },
                "owner": {
                    "$ref": "#/definitions/Sender"
                },
                "html_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "description": {
                    "type": "string"
                },
                "fork": {
                    "type": "boolean"
                },
                "url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "forks_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "keys_url": {
                    "type": "string"
                },
                "collaborators_url": {
                    "type": "string"
                },
                "teams_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "hooks_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "issue_events_url": {
                    "type": "string"
                },
                "events_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "assignees_url": {
                    "type": "string"
                },
                "branches_url": {
                    "type": "string"
                },
                "tags_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "blobs_url": {
                    "type": "string"
                },
                "git_tags_url": {
                    "type": "string"
                },
                "git_refs_url": {
                    "type": "string"
                },
                "trees_url": {
                    "type": "string"
                },
                "statuses_url": {
                    "type": "string"
                },
                "languages_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "stargazers_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "contributors_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "subscribers_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "subscription_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "commits_url": {
                    "type": "string"
                },
                "git_commits_url": {
                    "type": "string"
                },
                "comments_url": {
                    "type": "string"
                },
                "issue_comment_url": {
                    "type": "string"
                },
                "contents_url": {
                    "type": "string"
                },
                "compare_url": {
                    "type": "string"
                },
                "merges_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "archive_url": {
                    "type": "string"
                },
                "downloads_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "issues_url": {
                    "type": "string"
                },
                "pulls_url": {
                    "type": "string"
                },
                "milestones_url": {
                    "type": "string"
                },
                "notifications_url": {
                    "type": "string"
                },
                "labels_url": {
                    "type": "string"
                },
                "releases_url": {
                    "type": "string"
                },
                "deployments_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "created_at": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "pushed_at": {
                    "type": "integer"
                },
                "git_url": {
                    "type": "string"
                },
                "ssh_url": {
                    "type": "string"
                },
                "clone_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ],
                    "qt-uri-extensions": [
                        ".git"
                    ]
                },
                "svn_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "homepage": {
                    "type": "null"
                },
                "size": {
                    "type": "integer"
                },
                "stargazers_count": {
                    "type": "integer"
                },
                "watchers_count": {
                    "type": "integer"
                },
                "language": {
                    "type": "string"
                },
                "has_issues": {
                    "type": "boolean"
                },
                "has_projects": {
                    "type": "boolean"
                },
                "has_downloads": {
                    "type": "boolean"
                },
                "has_wiki": {
                    "type": "boolean"
                },
                "has_pages": {
                    "type": "boolean"
                },
                "forks_count": {
                    "type": "integer"
                },
                "mirror_url": {
                    "type": "null"
                },
                "archived": {
                    "type": "boolean"
                },
                "open_issues_count": {
                    "type": "integer"
                },
                "license": {
                    "type": "null"
                },
                "forks": {
                    "type": "integer"
                },
                "open_issues": {
                    "type": "integer"
                },
                "watchers": {
                    "type": "integer"
                },
                "default_branch": {
                    "type": "string"
                },
                "stargazers": {
                    "type": "integer"
                },
                "master_branch": {
                    "type": "string"
                }
            },
            "required": [],
            "title": "Repository"
        },
        "Sender": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "node_id": {
                    "type": "string"
                },
                "avatar_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "gravatar_id": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "html_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "followers_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "following_url": {
                    "type": "string"
                },
                "gists_url": {
                    "type": "string"
                },
                "starred_url": {
                    "type": "string"
                },
                "subscriptions_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "organizations_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "repos_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "events_url": {
                    "type": "string"
                },
                "received_events_url": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "type": {
                    "type": "string"
                },
                "site_admin": {
                    "type": "boolean"
                }
            },
            "required": [],
            "title": "Sender"
        }
    }
}

=== janhybs/ci-hpc/cihpc/common/utils/git/webhooks/push_hook/example.json
{
  "ref": "refs/heads/master",
  "before": "c2c5434853e6c1c712b363bec9805dfefe6d7bb6",
  "after": "e87eead22e741dafb58355b9a6cbcd632c8f3704",
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/janhybs/bench-stat/compare/c2c5434853e6...e87eead22e74",
  "commits": [
    {
      "id": "e87eead22e741dafb58355b9a6cbcd632c8f3704",
      "tree_id": "7e8ceefacd592f5a0a151b51b95d6cc9b28af5cd",
      "distinct": true,
      "message": "Change L3 array size from 32 to 44",
      "timestamp": "2018-11-19T08:53:54+01:00",
      "url": "https://github.com/janhybs/bench-stat/commit/e87eead22e741dafb58355b9a6cbcd632c8f3704",
      "author": {
        "name": "Jan Hybš",
        "email": "894428+janhybs@users.noreply.github.com",
        "username": "janhybs"
      },
      "committer": {
        "name": "GitHub",
        "email": "noreply@github.com",
        "username": "web-flow"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "benchmarks/main.cc"
      ]
    }
  ],
  "head_commit": {
    "id": "e87eead22e741dafb58355b9a6cbcd632c8f3704",
    "tree_id": "7e8ceefacd592f5a0a151b51b95d6cc9b28af5cd",
    "distinct": true,
    "message": "Change L3 array size from 32 to 44",
    "timestamp": "2018-11-19T08:53:54+01:00",
    "url": "https://github.com/janhybs/bench-stat/commit/e87eead22e741dafb58355b9a6cbcd632c8f3704",
    "author": {
      "name": "Jan Hybš",
      "email": "894428+janhybs@users.noreply.github.com",
      "username": "janhybs"
    },
    "committer": {
      "name": "GitHub",
      "email": "noreply@github.com",
      "username": "web-flow"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "benchmarks/main.cc"
    ]
  },
  "repository": {
    "id": 91433299,
    "node_id": "MDEwOlJlcG9zaXRvcnk5MTQzMzI5OQ==",
    "name": "bench-stat",
    "full_name": "janhybs/bench-stat",
    "private": false,
    "owner": {
      "name": "janhybs",
      "email": "894428+janhybs@users.noreply.github.com",
      "login": "janhybs",
      "id": 894428,
      "node_id": "MDQ6VXNlcjg5NDQyOA==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/894428?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/janhybs",
      "html_url": "https://github.com/janhybs",
      "followers_url": "https://api.github.com/users/janhybs/followers",
      "following_url": "https://api.github.com/users/janhybs/following{/other_user}",
      "gists_url": "https://api.github.com/users/janhybs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/janhybs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/janhybs/subscriptions",
      "organizations_url": "https://api.github.com/users/janhybs/orgs",
      "repos_url": "https://api.github.com/users/janhybs/repos",
      "events_url": "https://api.github.com/users/janhybs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/janhybs/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/janhybs/bench-stat",
    "description": "Simple repository containing benchmarks simulating numerical computing software",
    "fork": false,
    "url": "https://github.com/janhybs/bench-stat",
    "forks_url": "https://api.github.com/repos/janhybs/bench-stat/forks",
    "keys_url": "https://api.github.com/repos/janhybs/bench-stat/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/janhybs/bench-stat/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/janhybs/bench-stat/teams",
    "hooks_url": "https://api.github.com/repos/janhybs/bench-stat/hooks",
    "issue_events_url": "https://api.github.com/repos/janhybs/bench-stat/issues/events{/number}",
    "events_url": "https://api.github.com/repos/janhybs/bench-stat/events",
    "assignees_url": "https://api.github.com/repos/janhybs/bench-stat/assignees{/user}",
    "branches_url": "https://api.github.com/repos/janhybs/bench-stat/branches{/branch}",
    "tags_url": "https://api.github.com/repos/janhybs/bench-stat/tags",
    "blobs_url": "https://api.github.com/repos/janhybs/bench-stat/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/janhybs/bench-stat/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/janhybs/bench-stat/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/janhybs/bench-stat/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/janhybs/bench-stat/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/janhybs/bench-stat/languages",
    "stargazers_url": "https://api.github.com/repos/janhybs/bench-stat/stargazers",
    "contributors_url": "https://api.github.com/repos/janhybs/bench-stat/contributors",
    "subscribers_url": "https://api.github.com/repos/janhybs/bench-stat/subscribers",
    "subscription_url": "https://api.github.com/repos/janhybs/bench-stat/subscription",
    "commits_url": "https://api.github.com/repos/janhybs/bench-stat/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/janhybs/bench-stat/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/janhybs/bench-stat/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/janhybs/bench-stat/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/janhybs/bench-stat/contents/{+path}",
    "compare_url": "https://api.github.com/repos/janhybs/bench-stat/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/janhybs/bench-stat/merges",
    "archive_url": "https://api.github.com/repos/janhybs/bench-stat/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/janhybs/bench-stat/downloads",
    "issues_url": "https://api.github.com/repos/janhybs/bench-stat/issues{/number}",
    "pulls_url": "https://api.github.com/repos/janhybs/bench-stat/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/janhybs/bench-stat/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/janhybs/bench-stat/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/janhybs/bench-stat/labels{/name}",
    "releases_url": "https://api.github.com/repos/janhybs/bench-stat/releases{/id}",
    "deployments_url": "https://api.github.com/repos/janhybs/bench-stat/deployments",
    "created_at": 1494922643,
    "updated_at": "2018-07-30T10:22:01Z",
    "pushed_at": 1542614035,
    "git_url": "git://github.com/janhybs/bench-stat.git",
    "ssh_url": "git@github.com:janhybs/bench-stat.git",
    "clone_url": "https://github.com/janhybs/bench-stat.git",
    "svn_url": "https://github.com/janhybs/bench-stat",
    "homepage": null,
    "size": 124,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "C++",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 1,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "stargazers": 0,
    "master_branch": "master"
  },
  "pusher": {
    "name": "janhybs",
    "email": "894428+janhybs@users.noreply.github.com"
  },
  "sender": {
    "login": "janhybs",
    "id": 894428,
    "node_id": "MDQ6VXNlcjg5NDQyOA==",
    "avatar_url": "https://avatars3.githubusercontent.com/u/894428?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/janhybs",
    "html_url": "https://github.com/janhybs",
    "followers_url": "https://api.github.com/users/janhybs/followers",
    "following_url": "https://api.github.com/users/janhybs/following{/other_user}",
    "gists_url": "https://api.github.com/users/janhybs/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/janhybs/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/janhybs/subscriptions",
    "organizations_url": "https://api.github.com/users/janhybs/orgs",
    "repos_url": "https://api.github.com/users/janhybs/repos",
    "events_url": "https://api.github.com/users/janhybs/events{/privacy}",
    "received_events_url": "https://api.github.com/users/janhybs/received_events",
    "type": "User",
    "site_admin": false
  }
}
