=== janhybs/ci-hpc/cfg/flow123d/.profiler-docs/profiler.json.scheme.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Profiler",
    "definitions": {
        "Profiler": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "program-name": {
                    "type": "string"
                },
                "program-version": {
                    "type": "string"
                },
                "program-branch": {
                    "type": "string"
                },
                "program-revision": {
                    "type": "string"
                },
                "program-build": {
                    "type": "string"
                },
                "timer-resolution": {
                    "type": "string"
                },
                "task-description": {
                    "type": "string"
                },
                "task-size": {
                    "type": "string",
                    "format": "integer"
                },
                "run-process-count": {
                    "type": "string",
                    "format": "integer"
                },
                "run-started-at": {
                    "type": "string"
                },
                "run-finished-at": {
                    "type": "string"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Child"
                    }
                }
            },
            "required": [
                "children",
                "program-branch",
                "program-build",
                "program-name",
                "program-revision",
                "program-version",
                "run-finished-at",
                "run-process-count",
                "run-started-at",
                "task-description",
                "task-size",
                "timer-resolution"
            ],
            "title": "Profiler"
        },
        "Child": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "tag": {
                    "type": "string"
                },
                "file-path": {
                    "type": "string"
                },
                "file-line": {
                    "type": "string",
                    "format": "integer"
                },
                "function": {
                    "type": "string"
                },
                "cumul-time-min": {
                    "type": "string"
                },
                "cumul-time-max": {
                    "type": "string"
                },
                "cumul-time-sum": {
                    "type": "string"
                },
                "call-count-min": {
                    "type": "string",
                    "format": "integer"
                },
                "call-count-max": {
                    "type": "string",
                    "format": "integer"
                },
                "call-count-sum": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-alloc-min": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-alloc-max": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-alloc-sum": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-dealloc-min": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-dealloc-max": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-dealloc-sum": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-peak-min": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-peak-max": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-peak-sum": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-alloc-called-min": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-alloc-called-max": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-alloc-called-sum": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-dealloc-called-min": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-dealloc-called-max": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-dealloc-called-sum": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-petsc-diff-min": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-petsc-diff-max": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-petsc-diff-sum": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-petsc-peak-min": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-petsc-peak-max": {
                    "type": "string",
                    "format": "integer"
                },
                "memory-petsc-peak-sum": {
                    "type": "string",
                    "format": "integer"
                },
                "percent": {
                    "type": "string"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Child"
                    }
                }
            },
            "required": [
                "call-count-max",
                "call-count-min",
                "call-count-sum",
                "cumul-time-max",
                "cumul-time-min",
                "cumul-time-sum",
                "file-line",
                "file-path",
                "function",
                "memory-alloc-called-max",
                "memory-alloc-called-min",
                "memory-alloc-called-sum",
                "memory-alloc-max",
                "memory-alloc-min",
                "memory-alloc-sum",
                "memory-dealloc-called-max",
                "memory-dealloc-called-min",
                "memory-dealloc-called-sum",
                "memory-dealloc-max",
                "memory-dealloc-min",
                "memory-dealloc-sum",
                "memory-peak-max",
                "memory-peak-min",
                "memory-peak-sum",
                "memory-petsc-diff-max",
                "memory-petsc-diff-min",
                "memory-petsc-diff-sum",
                "memory-petsc-peak-max",
                "memory-petsc-peak-min",
                "memory-petsc-peak-sum",
                "percent",
                "tag"
            ],
            "title": "Child"
        }
    }
}

=== janhybs/ci-hpc/cfg/flow123d/.profiler-docs/profiler_info_18.08.14_15-54-12.log.json
{
    "program-name": "Flow123d",
    "program-version": "3.0.0",
    "program-branch": "master",
    "program-revision": "9cf00fa",
    "program-build": "Jul 17 2018, 12:50:13 flags: -g -O0 -Wall -Wno-unused-local-typedefs -Wno-deprecated-declarations -std=c++11",
    "timer-resolution": "0.000047470",
    "task-description": "Constant flow and advective transport.",
    "task-size": "15312",
    "run-process-count": "1",
    "run-started-at": "08\/14\/18 15:54:12",
    "run-finished-at": "08\/14\/18 15:54:19",
    "children": [
        {
            "tag": "Whole Program",
            "file-path": "\/src\/system\/sys_profiler.cc",
            "file-line": "297",
            "function": "",
            "cumul-time-min": "7.7818813049999997",
            "cumul-time-max": "7.7818813049999997",
            "cumul-time-sum": "7.7818813049999997",
            "call-count-min": "1",
            "call-count-max": "1",
            "call-count-sum": "1",
            "memory-alloc-min": "101387769",
            "memory-alloc-max": "101387769",
            "memory-alloc-sum": "101387769",
            "memory-dealloc-min": "101140886",
            "memory-dealloc-max": "101140886",
            "memory-dealloc-sum": "101140886",
            "memory-peak-min": "-52827",
            "memory-peak-max": "-52827",
            "memory-peak-sum": "-52827",
            "memory-alloc-called-min": "761373",
            "memory-alloc-called-max": "761373",
            "memory-alloc-called-sum": "761373",
            "memory-dealloc-called-min": "758731",
            "memory-dealloc-called-max": "758731",
            "memory-dealloc-called-sum": "758731",
            "memory-petsc-diff-min": "487882752",
            "memory-petsc-diff-max": "487882752",
            "memory-petsc-diff-sum": "487882752",
            "memory-petsc-peak-min": "117035008",
            "memory-petsc-peak-max": "117035008",
            "memory-petsc-peak-sum": "117035008",
            "percent": "100",
            "children": [
                {
                    "tag": "Application::run",
                    "file-path": "\/src\/main.cc",
                    "file-line": "298",
                    "function": "run",
                    "cumul-time-min": "7.5888859630000001",
                    "cumul-time-max": "7.5888859630000001",
                    "cumul-time-sum": "7.5888859630000001",
                    "call-count-min": "1",
                    "call-count-max": "1",
                    "call-count-sum": "1",
                    "memory-alloc-min": "101356031",
                    "memory-alloc-max": "101356031",
                    "memory-alloc-sum": "101356031",
                    "memory-dealloc-min": "85705485",
                    "memory-dealloc-max": "85705485",
                    "memory-dealloc-sum": "85705485",
                    "memory-peak-min": "-52827",
                    "memory-peak-max": "-52827",
                    "memory-peak-sum": "-52827",
                    "memory-alloc-called-min": "761264",
                    "memory-alloc-called-max": "761264",
                    "memory-alloc-called-sum": "761264",
                    "memory-dealloc-called-min": "602395",
                    "memory-dealloc-called-max": "602395",
                    "memory-dealloc-called-sum": "602395",
                    "memory-petsc-diff-min": "401346560",
                    "memory-petsc-diff-max": "401346560",
                    "memory-petsc-diff-sum": "401346560",
                    "memory-petsc-peak-min": "117035008",
                    "memory-petsc-peak-max": "117035008",
                    "memory-petsc-peak-sum": "117035008",
                    "percent": "97.519939787876268",
                    "children": [
                        {
                            "tag": "HC run simulation",
                            "file-path": "\/src\/coupling\/hc_explicit_sequential.cc",
                            "file-line": "200",
                            "function": "run_simulation",
                            "cumul-time-min": "5.8558225310000003",
                            "cumul-time-max": "5.8558225310000003",
                            "cumul-time-sum": "5.8558225310000003",
                            "call-count-min": "1",
                            "call-count-max": "1",
                            "call-count-sum": "1",
                            "memory-alloc-min": "66730777",
                            "memory-alloc-max": "66730777",
                            "memory-alloc-sum": "66730777",
                            "memory-dealloc-min": "65689488",
                            "memory-dealloc-max": "65689488",
                            "memory-dealloc-sum": "65689488",
                            "memory-peak-min": "-52827",
                            "memory-peak-max": "-52827",
                            "memory-peak-sum": "-52827",
                            "memory-alloc-called-min": "348965",
                            "memory-alloc-called-max": "348965",
                            "memory-alloc-called-sum": "348965",
                            "memory-dealloc-called-min": "348775",
                            "memory-dealloc-called-max": "348775",
                            "memory-dealloc-called-sum": "348775",
                            "memory-petsc-diff-min": "229642240",
                            "memory-petsc-diff-max": "229642240",
                            "memory-petsc-diff-sum": "229642240",
                            "memory-petsc-peak-min": "117035008",
                            "memory-petsc-peak-max": "117035008",
                            "memory-petsc-peak-sum": "117035008",
                            "percent": "77.163137772136267",
                            "children": [
                                {
                                    "tag": "OutputTime::write_time_frame",
                                    "file-path": "\/src\/io\/output_time.cc",
                                    "file-line": "201",
                                    "function": "write_time_frame",
                                    "cumul-time-min": "0.031380018000000003",
                                    "cumul-time-max": "0.031380018000000003",
                                    "cumul-time-sum": "0.031380018000000003",
                                    "call-count-min": "1",
                                    "call-count-max": "1",
                                    "call-count-sum": "1",
                                    "memory-alloc-min": "81323",
                                    "memory-alloc-max": "81323",
                                    "memory-alloc-sum": "81323",
                                    "memory-dealloc-min": "204059",
                                    "memory-dealloc-max": "204059",
                                    "memory-dealloc-sum": "204059",
                                    "memory-peak-min": "69909",
                                    "memory-peak-max": "69909",
                                    "memory-peak-sum": "69909",
                                    "memory-alloc-called-min": "98",
                                    "memory-alloc-called-max": "98",
                                    "memory-alloc-called-sum": "98",
                                    "memory-dealloc-called-min": "102",
                                    "memory-dealloc-called-max": "102",
                                    "memory-dealloc-called-sum": "102",
                                    "memory-petsc-diff-min": "0",
                                    "memory-petsc-diff-max": "0",
                                    "memory-petsc-diff-sum": "0",
                                    "memory-petsc-peak-min": "117035008",
                                    "memory-petsc-peak-max": "117035008",
                                    "memory-petsc-peak-sum": "117035008",
                                    "percent": "0.53587720314060183"
                                },
                                {
                                    "tag": "TOS-output data",
                                    "file-path": "\/src\/transport\/transport_operator_splitting.cc",
                                    "file-line": "232",
                                    "function": "output_data",
                                    "cumul-time-min": "0.38904055100000001",
                                    "cumul-time-max": "0.38904055100000001",
                                    "cumul-time-sum": "0.38904055100000001",
                                    "call-count-min": "10",
                                    "call-count-max": "10",
                                    "call-count-sum": "10",
                                    "memory-alloc-min": "18184723",
                                    "memory-alloc-max": "18184723",
                                    "memory-alloc-sum": "18184723",
                                    "memory-dealloc-min": "18184723",
                                    "memory-dealloc-max": "18184723",
                                    "memory-dealloc-sum": "18184723",
                                    "memory-peak-min": "-52827",
                                    "memory-peak-max": "-52827",
                                    "memory-peak-sum": "-52827",
                                    "memory-alloc-called-min": "31522",
                                    "memory-alloc-called-max": "31522",
                                    "memory-alloc-called-sum": "31522",
                                    "memory-dealloc-called-min": "31522",
                                    "memory-dealloc-called-max": "31522",
                                    "memory-dealloc-called-sum": "31522",
                                    "memory-petsc-diff-min": "0",
